#ifndef TEKO_SEMIBOLD_CONFIG_H
#define TEKO_SEMIBOLD_CONFIG_H

#include "stdint.h"

typedef uint16_t LCD_FontSize;

#define LCD_FONT_TEKO_SEMIBOLD_10 ((LCD_FontSize)10U)
#define LCD_FONT_TEKO_SEMIBOLD_14 ((LCD_FontSize)14U)
#define LCD_FONT_TEKO_SEMIBOLD_16 ((LCD_FontSize)16U)
#define LCD_FONT_TEKO_SEMIBOLD_20 ((LCD_FontSize)20U)
#define LCD_FONT_TEKO_SEMIBOLD_24 ((LCD_FontSize)24U)
#define LCD_FONT_TEKO_SEMIBOLD_28 ((LCD_FontSize)28U)
#define LCD_FONT_TEKO_SEMIBOLD_34 ((LCD_FontSize)34U)
#define LCD_FONT_TEKO_SEMIBOLD_48 ((LCD_FontSize)48U)
#define LCD_FONT_TEKO_SEMIBOLD_72 ((LCD_FontSize)72U)
#define LCD_FONT_TEKO_SEMIBOLD_96 ((LCD_FontSize)96U)
#define LCD_FONT_TEKO_SEMIBOLD_128 ((LCD_FontSize)128U)
#define LCD_FONT_TEKO_SEMIBOLD_144 ((LCD_FontSize)144U)
#define LCD_FONT_TEKO_SEMIBOLD_256 ((LCD_FontSize)256U)

#endif /* TEKO_SEMIBOLD_CONFIG_H */
